export const NATIONALITY_MAP = {
  "Afghan": "Afghanistan",
  "AFG": "Afghanistan",
  "Albanian": "Albania",
  "ALB": "Albania",
  "Algerian": "Algeria",
  "ALG": "Algeria",
  "DZA": "Algeria",
  "American": "United States",
  "USA": "United States",
  "Andorran": "Andorra",
  "AND": "Andorra",
  "Angolan": "Angola",
  "ANG": "Angola",
  "AGO": "Angola",
  "Argentinian": "Argentina",
  "ARG": "Argentina",
  "Armenian": "Armenia",
  "ARM": "Armenia",
  "Australian": "Australia",
  "AUS": "Australia",
  "Austrian": "Austria",
  "AUT": "Austria",
  "Azerbaijani": "Azerbaijan",
  "AZE": "Azerbaijan",
  "Bahamian": "Bahamas",
  "BAH": "Bahamas",
  "Bahraini": "Bahrain",
  "BHR": "Bahrain",
  "Bangladeshi": "Bangladesh",
  "BAN": "Bangladesh",
  "Barbadian": "Barbados",
  "BAR": "Barbados",
  "Belarusian": "Belarus",
  "BLR": "Belarus",
  "Belgian": "Belgium",
  "BEL": "Belgium",
  "Belizean": "Belize",
  "BLZ": "Belize",
  "Beninese": "Benin",
  "BEN": "Benin",
  "Bhutanese": "Bhutan",
  "BHU": "Bhutan",
  "Bolivian": "Bolivia",
  "BOL": "Bolivia",
  "Bosnian": "Bosnia and Herzegovina",
  "BIH": "Bosnia and Herzegovina",
  "BOS": "Bosnia and Herzegovina",
  "Botswanan": "Botswana",
  "BOT": "Botswana",
  "Brazilian": "Brazil",
  "BRA": "Brazil",
  "BRE": "Brazil",
  "British": "United Kingdom",
  "GBR": "United Kingdom",
  "Bruneian": "Brunei",
  "BRU": "Brunei",
  "Bulgarian": "Bulgaria",
  "BUL": "Bulgaria",
  "Burkinabe": "Burkina Faso",
  "BUR": "Burkina Faso",
  "Burundian": "Burundi",
  "BDI": "Burundi",
  "Cambodian": "Cambodia",
  "CAM": "Cambodia",
  "Cameroonian": "Cameroon",
  "CMR": "Cameroon",
  "Canadian": "Canada",
  "CAN": "Canada",
  "Cape Verdean": "Cape Verde",
  "CPV": "Cape Verde",
  "Central African": "Central African Republic",
  "CAF": "Central African Republic",
  "Chadian": "Chad",
  "CHA": "Chad",
  "Chilean": "Chile",
  "CHI": "Chile",
  "CHL": "Chile",
  "Chinese": "China",
  "CHN": "China",
  "Colombian": "Colombia",
  "COL": "Colombia",
  "Comoran": "Comoros",
  "COM": "Comoros",
  "Congolese": "Congo",
  "CON": "Congo",
  "CGO": "Congo",
  "COG": "Congo",
  "RCO": "DR Congo",
  "Costa Rican": "Costa Rica",
  "CRC": "Costa Rica",
  "Croatian": "Croatia",
  "CRO": "Croatia",
  "HRV": "Croatia",
  "Cuban": "Cuba",
  "CUB": "Cuba",
  "Cypriot": "Cyprus",
  "CYP": "Cyprus",
  "Czech": "Czech Republic",
  "CZE": "Czech Republic",
  "Danish": "Denmark",
  "DEN": "Denmark",
  "DNK": "Denmark",
  "Djiboutian": "Djibouti",
  "DJI": "Djibouti",
  "Dominican": "Dominican Republic",
  "DOM": "Dominican Republic",
  "Dutch": "Netherlands",
  "NED": "Netherlands",
  "NLD": "Netherlands",
  "HOL": "Netherlands",
  "Ecuadorean": "Ecuador",
  "ECU": "Ecuador",
  "Egyptian": "Egypt",
  "EGY": "Egypt",
  "Emirati": "United Arab Emirates",
  "UAE": "United Arab Emirates",
  "English": "United Kingdom",
  "ENG": "United Kingdom",
  "Equatorial Guinean": "Equatorial Guinea",
  "EQG": "Equatorial Guinea",
  "GUN": "Guinea-Bissau",
  "Eritrean": "Eritrea",
  "ERI": "Eritrea",
  "Estonian": "Estonia",
  "EST": "Estonia",
  "Ethiopian": "Ethiopia",
  "ETH": "Ethiopia",
  "Fijian": "Fiji",
  "FIJ": "Fiji",
  "Finnish": "Finland",
  "FIN": "Finland",
  "French": "France",
  "FRA": "France",
  "Gabonese": "Gabon",
  "GAB": "Gabon",
  "Gambian": "Gambia",
  "GAM": "Gambia",
  "Georgian": "Georgia",
  "GEO": "Georgia",
  "German": "Germany",
  "GER": "Germany",
  "DEU": "Germany",
  "Ghanaian": "Ghana",
  "GHA": "Ghana",
  "Greek": "Greece",
  "GRE": "Greece",
  "GRC": "Greece",
  "Grenadian": "Grenada",
  "GRN": "Grenada",
  "Guatemalan": "Guatemala",
  "GUA": "Guatemala",
  "Guinean": "Guinea",
  "GNB": 'Guinea',
  "GUI": "Guinea",
  "Guyanese": "Guyana",
  "GUY": "Guyana",
  "Haitian": "Haiti",
  "HAI": "Haiti",
  "Honduran": "Honduras",
  "HON": "Honduras",
  "Hungarian": "Hungary",
  "HUN": "Hungary",
  "Icelander": "Iceland",
  "ISL": "Iceland",
  "Indian": "India",
  "IND": "India",
  "Indonesian": "Indonesia",
  "INA": "Indonesia",
  "Iranian": "Iran",
  "IRI": "Iran",
  "IRN": "Iran",
  "Iraqi": "Iraq",
  "IRQ": "Iraq",
  "Irish": "Ireland",
  "IRL": "Ireland",
  "Israeli": "Israel",
  "ISR": "Israel",
  "Italian": "Italy",
  "ITA": "Italy",
  "Ivorian": "Ivory Coast",
  "CIV": "Ivory Coast",
  "IVO": "Ivory Coast",
  "Jamaican": "Jamaica",
  "JAM": "Jamaica",
  "Japanese": "Japan",
  "JPN": "Japan",
  "Jordanian": "Jordan",
  "JOR": "Jordan",
  "Kazakh": "Kazakhstan",
  "KAZ": "Kazakhstan",
  "Kenyan": "Kenya",
  "KEN": "Kenya",
  "Kuwaiti": "Kuwait",
  "KUW": "Kuwait",
  "Kyrgyz": "Kyrgyzstan",
  "KGZ": "Kyrgyzstan",
  "Lao": "Laos",
  "LAO": "Laos",
  "Latvian": "Latvia",
  "LAT": "Latvia",
  "Lebanese": "Lebanon",
  "LIB": "Lebanon",
  "Liberian": "Liberia",
  "LBR": "Liberia",
  "Libyan": "Libya",
  "LBA": "Libya",
  "Liechtenstein": "Liechtenstein",
  "LIE": "Liechtenstein",
  "Lithuanian": "Lithuania",
  "LTU": "Lithuania",
  "Luxembourgish": "Luxembourg",
  "LUX": "Luxembourg",
  "Macedonian": "North Macedonia",
  "MKD": "North Macedonia",
  "Malagasy": "Madagascar",
  "MAD": "Madagascar",
  "Malawian": "Malawi",
  "MAW": "Malawi",
  "Malaysian": "Malaysia",
  "MAS": "Malaysia",
  "Maldivian": "Maldives",
  "MDV": "Maldives",
  "Malian": "Mali",
  "MLI": "Mali",
  "MAI": "Mali",
  "Maltese": "Malta",
  "MLT": "Malta",
  "Mauritanian": "Mauritania",
  "MTN": "Mauritania",
  "Mauritian": "Mauritius",
  "MRI": "Mauritius",
  "Mexican": "Mexico",
  "MEX": "Mexico",
  "Moldovan": "Moldova",
  "MDA": "Moldova",
  "Monegasque": "Monaco",
  "MON": "Monaco",
  "Mongolian": "Mongolia",
  "MGL": "Mongolia",
  "Montenegrin": "Montenegro",
  "MNE": "Montenegro",
  "Moroccan": "Morocco",
  "MAR": "Morocco",
  "Mozambican": "Mozambique",
  "MOZ": "Mozambique",
  "Namibian": "Namibia",
  "NAM": "Namibia",
  "Nepalese": "Nepal",
  "NEP": "Nepal",
  "New Zealander": "New Zealand",
  "NZL": "New Zealand",
  "Nicaraguan": "Nicaragua",
  "NCA": "Nicaragua",
  "Nigerian": "Nigeria",
  "NGA": "Nigeria",
  "NIG": "Nigeria",
  "Norwegian": "Norway",
  "NOR": "Norway",
  "Omani": "Oman",
  "OMA": "Oman",
  "Pakistani": "Pakistan",
  "PAK": "Pakistan",
  "Palestinian": "Palestine",
  "PLE": "Palestine",
  "Panamanian": "Panama",
  "PAN": "Panama",
  "Papua New Guinean": "Papua New Guinea",
  "PNG": "Papua New Guinea",
  "Paraguayan": "Paraguay",
  "PAR": "Paraguay",
  "PRY": "Paraguay",
  "Peruvian": "Peru",
  "PER": "Peru",
  "Philippine": "Philippines",
  "PHI": "Philippines",
  "Polish": "Poland",
  "POL": "Poland",
  "Portuguese": "Portugal",
  "PRT": "Portugal",
  "POR": "Portugal",
  "Qatari": "Qatar",
  "QAT": "Qatar",
  "Romanian": "Romania",
  "ROU": "Romania",
  "Russian": "Russia",
  "RUS": "Russia",
  "Rwandan": "Rwanda",
  "RWA": "Rwanda",
  "Saint Lucian": "Saint Lucia",
  "LCA": "Saint Lucia",
  "Salvadoran": "El Salvador",
  "SLV": "El Salvador",
  "Samoan": "Samoa",
  "SAM": "Samoa",
  "Saudi": "Saudi Arabia",
  "KSA": "Saudi Arabia",
  "Scottish": "Scotland",
  "SCO": "Scotland",
  "SCT": "Scotland",
  "Senegalese": "Senegal",
  "SEN": "Senegal",
  "Serbian": "Serbia",
  "SRB": "Serbia",
  "SER": "Serbia",
  "Seychellois": "Seychelles",
  "SEY": "Seychelles",
  "Sierra Leonean": "Sierra Leone",
  "SLE": "Sierra Leone",
  "Singaporean": "Singapore",
  "SGP": "Singapore",
  "Slovak": "Slovakia",
  "SVK": "Slovakia",
  "SVQ": "Slovakia",
  "Slovenian": "Slovenia",
  "SLO": "Slovenia",
  "Solomon Islander": "Solomon Islands",
  "SOL": "Solomon Islands",
  "Somali": "Somalia",
  "SOM": "Somalia",
  "South African": "South Africa",
  "RSA": "South Africa",
  "SAF": "South Africa",
  "South Korean": "South Korea",
  "CSU": "South Korea",
  "KOR": "South Korea",
  "KVX": "Kosovo",
  "KSV": "Kosovo",
  "South Sudanese": "South Sudan",
  "SSD": "South Sudan",
  "Spanish": "Spain",
  "ESP": "Spain",
  "Sri Lankan": "Sri Lanka",
  "SRI": "Sri Lanka",
  "Sudanese": "Sudan",
  "SUD": "Sudan",
  "Surinamer": "Suriname",
  "SUR": "Suriname",
  "Swazi": "Eswatini",
  "SWZ": "Eswatini",
  "Swedish": "Sweden",
  "SUE": "Sweden",
  "SWE": "Sweden",
  "Swiss": "Switzerland",
  "SUI": "Switzerland",
  "CHE": "Switzerland",
  "Syrian": "Syria",
  "SYR": "Syria",
  "Taiwanese": "Taiwan",
  "TPE": "Taiwan",
  "Tajik": "Tajikistan",
  "TJK": "Tajikistan",
  "Tanzanian": "Tanzania",
  "TAN": "Tanzania",
  "Thai": "Thailand",
  "THA": "Thailand",
  "Togolese": "Togo",
  "TOG": "Togo",
  "Tongan": "Tonga",
  "TGA": "Tonga",
  "Trinidadian": "Trinidad and Tobago",
  "TTO": "Trinidad and Tobago",
  "Tunisian": "Tunisia",
  "TUN": "Tunisia",
  "Turkish": "Turkey",
  "TUR": "Turkey",
  "Turkmen": "Turkmenistan",
  "TKM": "Turkmenistan",
  "Ugandan": "Uganda",
  "UGA": "Uganda",
  "Ukrainian": "Ukraine",
  "UKR": "Ukraine",
  "Uruguayan": "Uruguay",
  "URU": "Uruguay",
  "URY": "Uruguay",
  "Uzbek": "Uzbekistan",
  "OUZ": "Uzbekistan",
  "UZB": "Uzbekistan",
  "Venezuelan": "Venezuela",
  "VEN": "Venezuela",
  "Vietnamese": "Vietnam",
  "VIE": "Vietnam",
  "Yemeni": "Yemen",
  "YEM": "Yemen",
  "Zambian": "Zambia",
  "ZAM": "Zambia",
  "ZMB": "Zambia",
  "Zimbabwean": "Zimbabwe",
  "ZIM": "Zimbabwe"
};

